# Generated by Django 4.2.4 on 2023-09-10 17:37

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBeneficiario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiario', models.CharField(max_length=160)),
                ('descrizione', models.TextField(max_length=1500)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('sitoweb', models.URLField(null=True)),
                ('iduser', models.BigIntegerField()),
            ],
            options={
                'db_table': 'scadenzario_modelbeneficiario',
            },
        ),
        migrations.CreateModel(
            name='ModelScadenze',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiario', models.CharField(max_length=100)),
                ('datascadenza', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=19)),
                ('sollecito', models.BooleanField()),
                ('giorniritardo', models.SmallIntegerField(null=True)),
                ('datapagamento', models.DateField(null=True)),
                ('iduser', models.BigIntegerField()),
                ('idbeneficiario', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='scadenzario.modelbeneficiario')),
            ],
            options={
                'db_table': 'scadenzario_modelscadenze',
            },
        ),
        migrations.CreateModel(
            name='ModelRicevute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomeFile', models.CharField(max_length=150)),
                ('typeFile', models.CharField(max_length=50, null=True)),
                ('contentFile', models.FileField(upload_to='')),
                ('beneficiario', models.CharField(max_length=150)),
                ('path', models.CharField(max_length=1450, null=True)),
                ('scadenze', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_scadenze', to='scadenzario.modelscadenze')),
            ],
            options={
                'db_table': 'scadenzario_modelricevute',
            },
        ),
    ]
